const AXIOS_RESPONSE_TIMEOUT = 10000;
const BOT_UPTIME = 10000;

const DATA_FILE_PATH = './data/data.json';
const MARKDOWN = { "parse_mode": "Markdown" };
const ENTRY_TYPE_RESULT = 'result';
const ENTRY_TYPE_DATESHEET = 'datesheet';
const COMMAND_RESULTS = 'results';
const COMMAND_DATESHEETS = 'datesheets';
const COMMAND_SUBSCRIBE = 'subscribe';
const COMMAND_UNSUBSCRIBE = 'unsubscribe';

const ALL_ENTRY_TYPES = [ENTRY_TYPE_RESULT, ENTRY_TYPE_DATESHEET];
const COMMAND_ENTRY_LIST = [
    [COMMAND_RESULTS, ENTRY_TYPE_RESULT],
    [COMMAND_DATESHEETS, ENTRY_TYPE_DATESHEET]
];

const GRACEFUL_STOP_SIGNALS = ['SIGINT', 'SIGTERM', 'exit'];

export default {
    AXIOS_RESPONSE_TIMEOUT,
    BOT_UPTIME,
    DATA_FILE_PATH,
    MARKDOWN,
    ENTRY_TYPE_RESULT,
    ENTRY_TYPE_DATESHEET,
    COMMAND_RESULTS,
    COMMAND_DATESHEETS,
    COMMAND_SUBSCRIBE,
    COMMAND_UNSUBSCRIBE,
    ALL_ENTRY_TYPES,
    COMMAND_ENTRY_LIST,
    GRACEFUL_STOP_SIGNALS
}
